### ISSUE TITLE
ValueError: Seed must be between 0 and 2**32 - 1

### ISSUE THREAD

**Issue by kazumaxneo** [lbobay/CoreSimul#2]
Hi,
I ran the test code in python 3.8 or python 3.10 environment and got following error; indicating that the seed value is not appropriate.

$ python coresimul_master.py control.txt 
Launching pipeline with Python 3
Snake= 3
loc=   coresimul_master.py
Usage:  python coresimul_master.py   control.txt

### Welcome! ###

Output folder already exists. Previous files will be lost.
1. Reading the tree
['Samanta', 'Vincent', 'Jason', 'Pedro', 'B24', 'B29', 'coucou', 'B15', 'B19', 'hello', 'B2', 'B25', 'B32', 'B37', 'B13', 'B3', 'B5', 'B4', 'Michel56', 'B18', 'B35', 'B7', 'B26', 'B8', 'B11', 'B14', 'B10', 'B42', 'B33', 'B21', 'B1', 'B12', 'B17', 'B16']
Found  34 taxa in the tree
2. Extracting branch lengths and topology
3. Simulating

################
PARAMETERS: 
OUTPUT=  test/
Alignment Length=  50000 bp
GC%=  45.0 % (default=50%)
Branch rescaling=  0.9  (default=1, no rescaling)
Transition/Transversion bias, Kappa=  1.1  (default=1, no bias)
CODONS Frequency=  0.2,0.1,0.7 
STARTING GENOME=  none
SUBSTITUTION MODEL=  K2P with rate(s)  none
GAIN_RATE= none
LOSS_RATE= none
MIN_DELTA= 1
################

USAGE:
['simulation.py', '1715522310420', 'no', '1', 'none', 'none', 'K2P', 'none', 'none', '0.2,0.1,0.7', '1.1', '45.0', '50000', '1.0', '200', '0.9', 'test/']
Setting random seed: 1715522310420
Traceback (most recent call last):
  File "simulation.py", line 103, in <module>
    numpy.random.seed(int(rseed))
  File "mtrand.pyx", line 4789, in numpy.random.mtrand.seed
  File "mtrand.pyx", line 250, in numpy.random.mtrand.RandomState.seed
  File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
ValueError: Seed must be between 0 and 2**32 - 1

Perhaps I need to modify the seed value to be within the proper range or generate a random number seed in a more appropriate manner. Is there any way to correct this?

**Comment by lbobay** [comment]
Hi, I just checked and yes, it is simply because you gave it a seed that exceeds what Numpy can handle. Just make sure that the seed is below 2**32 - 1 (~4.29**9) and everything should be fine!

**Comment by kazumaxneo** [comment]
HI lbobay.

Thanks for responding.
It is a 32-bit limitation, I understand.
The error is simply I forgot to remove the comment on the RSEED line in the provided control.txt 
I was able to run without error after removing comment.
Many thanks.

best,
